### ISSUE TITLE
autoFunctorK should respect instances of result types

### ISSUE THREAD

**Issue by Odomontois** [typelevel/cats-tagless#10]
e.g.
```scala
@autoFunctorK
trait Foo[F[_]]{
   def int: F[Int]
}

//currently doesn't work
@autoFunctorK
trait Baz[F[_]]{
  def foo: Foo[F]
}
```

**Comment by kailuowang** [comment]
This is possible but might be a bit tricky. `@autoFunctorK` need to investigate all return types to determine what `FunctorK` instances for some return types would be needed to create a `FunctorK` instance for the algebra.

**Comment by joroKr21** [comment]
It probably wouldn't be too hard to construct a `PolyType` `F[_] => Foo[F, Bar[Baz[F]]]` and then try to summon an implicit instances of `FunctorK` for it. Could attempt that after #6 is complete though (which might take a long time).

**Comment by joroKr21** [comment]
You could also argue that there should be a `ContravariantK` and `FunctorK` should respect instances of it in method parameter positions :smile:

**Comment by Daenyth** [comment]
It would be excellent if this could also notice if `Foo[F]` has a `mapK` function itself, and use that if there's no `FunctorK[Foo]` instance, similar to how `flatMap` works with `for`

**Comment by joroKr21** [comment]
I don't think that's a good idea. It wouldn't generalize well. And after all you could trivially implement a `FunctorK` instance but you would be responsible for upholding the laws.

`for` is just the syntax sugar for `flatMap`, but it doesn't automatically give us a `FlatMap` instance.

**Comment by Daenyth** [comment]
Good point
