### ISSUE TITLE
Provide method parameter names and values in Instrument

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-tagless#126]
It would be nice to have access to names and values of the parameters for the given call.

Why would this be useful?

- generating keys for caching
- adding selected parameters as tags to a distributed tracing span
- logging selected parameters in an error handler added to the underlying algebra

This will likely be problematic because of the types, but maybe there's something we can do about this.

The basic idea: for an algebra like

```scala
trait Foo[F[_]] {
  def bar(a: String, b: Int): F[Int]
}
```

I imagine we could have a type like

```scala
trait Parameter[Constraints[_]] {
  type T
  def constraints: Constraints[T]
  def name: String
  def value: T //by name?
}
```

included in `Instrumentation`:

```scala
final case class Instrumentation[F[_], Constraints[_], A](
  value: F[A],
  algebraName: String,
  methodName: String,
  parameters: List[List[Parameter[Constraints]]],
)
```

and somehow define the constraints that we require each parameter to have, at the point of instrumenting:

```scala
val foo: Foo[IO] = ???

//Show[String] and Show[Int] would be required here
val instrumented: Foo[Instrumentation[IO, Show, *]] = foo.instrument[Show]

val result = instrumented.bar("baz", 42)

val stringified = result.parameters.head.map { param =>
  param.name + ": " + param.constraints.show(param.value)
}.mkString(", ") //a: "baz", b: 42
```

I think kinds aren't a problem in this particular case, as parameters will need to be values, so `*`-kinded things (exactly what `Constraints[_]` expects).

For multiple implicits (which I don't think would be a common case, as Show should be enough for most usages), one could define a custom case class with derivations from/to it based on other implicits:

```scala
final case class Constraints[A](show: Show[A], monoid: Monoid[A])
implicit def constraintsToShow[A](implicit constraints: Constraints[A]): Show[A] = ...
```

or something like `EList` (implicit evidence list), as seen in @non's talk: https://youtu.be/O78hnJuzQwA?t=1652

```scala
object foo {
  import cats.implicits._
  type Constraints[A] = Show[A] :/: Monoid[A] :/: ENil

  val constraints: Constraints[String] = ... //some implicit derivation?
}

object bar {
  import foo.constraints

  Show[String] //derives from Constraints[String]
}
```

**Comment by kubukoz** [comment]
For cases when one wouldn't need any constraints, I suppose we could utilize a type like `type NoConstraints[A] = Unit`. Sadly `Nothing` doesn't work with the shape of `Parameter` I proposed (unless we decide it's okay for a `def constraints: Nothing`-shaped method to throw exceptions, which I think wouldn't be so bad, as the shape implies the method has to throw or never terminate)

**Comment by kubukoz** [comment]
I also realized we might want to have some type class instances for the results of functions in the algebra. However, that, the parameters and whatever Instrument provides already seem orthogonal and could probably end up in different type classes.

For return types, another shape, similar to Parameter comes to mind:

```scala
final case class WithInstances[F[_], Constraints[_], T](
  constraints: Constraints[T],
  value: F[T]
)
```

Note the lack of the existential. We don't need it, because each method has exactly one return type, which isn't true for parameter types.

This would be composable with `Instrumented` too (`F` would be `Instrumented`, or the effect in `Instrumented` would be `WithInstances` - doesn't matter really).

So this would be defined like

```scala
trait SomeTC[Alg[_[_]]] {
  def withReturnInstances[F[_], Constraints[_]](alg: Alg[F]): Alg[WithInstances[F, Constraints, *]]
}
```

with syntax:

```scala
(??? : MyAlg[IO]).withReturnInstances[Semigroup]
```

That'd make it easier to e.g. combine results of a composition of multiple interpreters of an algebra, e.g. by concatenating two lists.

**Comment by kubukoz** [comment]
The whole thing turns out to be more complex than I thought. For example, guessing the type of "this has instances of `Constraints[A]` for all `A` in the set of `String, Int, Boolean, List[String]`. I made a reference implementation with shapeless and it kinda works, but there's a lot of extra work on the user's side that requires familiarity with shapeless (at least in the pieces of code that actually instrument an algebra).

See https://github.com/kubukoz/talks/blob/e11f06edd42e6ddc2df486ef586c7832e49af211/party-tricks-cats-tagless/src/main/scala/com/kubukoz/tagless/examples/TheFuture.scala

Some excerpts:

```scala
  @typeclass
  trait ReturnTyped[Alg[_[_]]] {
    type AllReturnTypes <: HList
    type AllReturnTypesWithInstances[Constraints[_]] <: HList

    def returnTyped[F[_], Constraints[_]](
      alg: Alg[F]
    )(
      implicit constraints: LiftAll.Aux[
        Constraints,
        AllReturnTypes,
        AllReturnTypesWithInstances[Constraints]
      ]
    ): Alg[ReturnType[F, Constraints, *]]
  }

  object ReturnTyped {

    type Aux[Alg[_[_]], AllReturnTypes_ <: HList, AllReturnTypesWithInstances_[_[_]] <: HList] =
      ReturnTyped[Alg] {
        type AllReturnTypes = AllReturnTypes_
        type AllReturnTypesWithInstances[F[_]] = AllReturnTypesWithInstances_[F]
      }
  }

    //usage - logging the return value of each method in an algebra using its Show instance

    def logResult[
      F[_]: FlatMap: cats.effect.Console,
      Alg[_[_]]: FunctorK,
      Params <: HList,
      ParamsWithInstances[_[_]] <: HList
    ](
      tag: String,
      alg: Alg[F]
    )(
      implicit returnTyped: ReturnTyped.Aux[Alg, Params, ParamsWithInstances],
      liftParamsToShow: LiftAll.Aux[Show, Params, ParamsWithInstances[Show]]
    ): Alg[F] =
      alg
        .returnTyped[Show]
        .mapK(
          λ[ReturnType[F, Show, *] ~> F] { rt =>
            rt.value.flatTap { result =>
              implicit val instance = rt.constraints

              cats.effect.Console[F].putStrLn(show"[$tag] Result was: $result")
            }
          }
        )

    val users: Users[IO] = ???

    val loggedInstance = logResult("users", users)
```

**Comment by kubukoz** [comment]
Turns out we can completely separate the effect out of these instrumentations, probably the same can be done with `Instrument`. The effect can be retrieved by using the original, un-instrumented instance in a `productK` with the instrumentation.

Also, `ReturnTyped` is now pretty much a transformation from `F` to `Constraints`:

```scala
  @typeclass
  trait ReturnTyped[Alg[_[_]]] {
    type AllReturnTypes[Constraints[_]] <: HList

    def returnTyped[F[_], Constraints[_]](
      alg: Alg[F]
    )(
      implicit constraints: LiftAll.Aux[
        Constraints,
        AllReturnTypes[cats.Id],
        AllReturnTypes[Constraints]
      ]
    ): Alg[Constraints]
  }
```

And the usage now looks like this:

```scala
def logResult[
  F[_]: FlatMap: cats.effect.Console,
  Alg[_[_]]: ApplyK,
  ParamsWithInstances[_[_]] <: HList
](
  tag: String,
  alg: Alg[F]
)(
  implicit returnTyped: ReturnTyped.Aux[Alg, ParamsWithInstances],
  liftParamsToShow: LiftAll.Aux[Show, ParamsWithInstances[cats.Id], ParamsWithInstances[
    Show
  ]]
): Alg[F] =
  alg.map2K(alg.returnTyped[Show])(
    λ[Tuple2K[F, Show, *] ~> F] {
      case Tuple2K(value, rt) =>
        value.flatTap { result =>
          implicit val instance = rt

          cats.effect.Console[F].putStrLn(show"[$tag] Result was: $result")
        }
    }
  )
```

**Comment by joroKr21** [comment]
> Turns out we can completely separate the effect out of these instrumentations, probably the same can be done with Instrument. The effect can be retrieved by using the original, un-instrumented instance in a productK with the instrumentation.

I think we considered that but decided `Instrument[F, A]` would be more convenient.
See PR #95 for some discussion.

We can probably extend `Instrument` with more type parameters `Instrument[F[_], A[_], R[_], T]` for the constraints or add another version `InstrumentConstrained`. There would also have to be a `Trivial[A]` typeclass which always resolves.

Some nice ideas here how to encode constructs like this: https://github.com/alexknvl/polymorphic

**Comment by kubukoz** [comment]
you had me at `[F[_], A[_], R[_], T]`...

I'll look at an extended Instrument then!
