### ISSUE TITLE
Trouble deriving instances for ApplicativeError/MonadError

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-tagless#133]
```scala
def invariantKApplicativeError[E]: InvariantK[ApplicativeError[*[_], E]] =
  Derive.invariantK[ApplicativeError[*[_], E]]
```

The above results in:

```scala
could not find implicit value of type cats.tagless.InvariantK[[F[_]]cats.ApplicativeError.CatchOnlyPartiallyApplied[T,F,E]]
```

which doesn't seem too helpful... 

An attempt to derive MonadError:

```scala
def invariantKMonadError[E]: InvariantK[MonadError[*[_], E]] =
  Derive.invariantK[MonadError[*[_], E]]
```

yields 

```scala
could not find implicit value of type cats.tagless.InvariantK[[F[_]]E => F[B]]
```

which is slightly more helpful. Implementing the instance helps, but not a lot:

```scala
implicit def functorKFunctionEffect[I, O]: FunctorK[Lambda[F[_] => I => F[O]]] = new FunctorK[Lambda[F[_] => I => F[O]]] {
      def mapK[F[_], G[_]](af: I => F[O])(fk: F ~> G): I => G[O] = i => fk(af(i))
    }
```

```scala
could not find implicit value of type cats.tagless.InvariantK[[F[_]]=> F[Boolean]]
```

and I implemented that too, but it's not being picked up:

```scala
could not find implicit value of type cats.tagless.InvariantK[[F[_]]=> F[Boolean]]
```

**Comment by joroKr21** [comment]
Do you have an idea how to improve the error message?

`CatchOnlyPartiallyApplied` is some type returned by a method in `ApplicativeError` - I bet it's using the well known trick to emulate partially applied type parameters for better type inference. Unfortunately there is nothing we can do here.

```scala
could not find implicit value of type cats.tagless.InvariantK[[F[_]]=> F[Boolean]]
```
What type is that? Is that a by-name parameter?
Sounds like something we should be able to fix, though some debugging is necessary.

**Comment by kubukoz** [comment]
That did look like a by-name, yeah. And now I realize that error with CatchOnlyPartiallyApplied was actually pretty reasonable :) if we can show the method that's missing an extra instance, that'll be pretty awesome, so I'm hopeful for #134!
