### ISSUE TITLE
Publish for scalajs 1.0

### ISSUE THREAD

**Issue by cosmin33** [typelevel/cats-tagless#136]
Tried to tackle this one but didn't even find the place to change scalajs version. I suspect many things are hidden under sbt-catalysts magic.. I cound use a few pointers from someone who  knows more.

**Comment by joroKr21** [comment]
We should remove sbt-catalyst 😞 But haven't found time to do it.
It's also black magic to me.

**Comment by joroKr21** [comment]
@kailuowang any idea how to override scalajs version from catalysts?

**Comment by larsrh** [comment]
Looks like this can be closed now: https://oss.sonatype.org/content/repositories/public/org/typelevel/cats-tagless-core_sjs1_2.13/0.12/
