### ISSUE TITLE
cats-tagless-macro doesn't work with bloop

### ISSUE THREAD

**Issue by ytaras** [typelevel/cats-tagless#20]
I am not sure if that's a [bloop](https://github.com/scalacenter/bloop) issue or cats-tagless issue, but when I try compilation with bloop compiler, looks like macro annotations are not being expanded.
If I try doing the same with sbt, everything compiles fine. 

I've been trying hard to enable more debugging output during macro generation but failed, any hits are appreciated. 

I've assembled simplest reproducible case in this repo: https://github.com/ytaras/tagless_failure_showcase

**Comment by kailuowang** [comment]
It's probably the scalameta macro not supported by bloop, and I doubt it will be supported. The plan is to move cats-tagless to scala-macro, though we don't have a timeline for that.

**Comment by kailuowang** [comment]
the core functionality of cats-tagless is no longer dependent on scala-meta-macros. 
Migrating to cats-tagless 0.5 without dependencies on `cats-tagless-legacy-macros` will likely fix this.
For an example of such migrations please see
https://github.com/iheartradio/thomas/pull/37/files

**Comment by joroKr21** [comment]
Cats-tagless has migrated to scala.reflect macro annotations in 0.7. Please reopen if the issue persists.
