### ISSUE TITLE
Derive implementation based on other type class instances

### ISSUE THREAD

**Issue by Fristi** [typelevel/cats-tagless#21]
## Use case

An example of one of my algebras:

```scala
trait Users[F[_]] {
  def login(username: String Refined Email, password: String Refined Password): F[Option[ExchangeResult]]
  def register(user: User, password: String Refined Password): F[Option[UserId]]
}
```

Each algebra is tested in isolation as most of them have side effects and therefore I test them against a real database.

Now in my service layer I use multiple algebras together to run a specific flow. These flows can fail and therefore a typical service method uses `EitherT[F, ErrType, Res]`. As I've tested the algebras already I can just stub them. I find myself writing this a lot:

```scala
class DummyUsers[F[_]: Applicative] extends Users[F] {
  def login(username: Refined[String, Email], password: Refined[String, Password]): F[Option[ExchangeResult]] =
    Applicative[F].pure(None)
  def register(user: User, password: Refined[String, Password]): F[Option[UserId]] =
    Applicative[F].pure(None)
}
```

As you can see here I constraint `F[_]` to be a `Applicative` such that I can use `Id` or `Writer` to be flexible in that regard. When I want to alter behavior, I subclass the `DummyUsers` class and I override the method.

This however generates a lot of boilerplate

## Solution: derive type class implementations
Given I have defined a `Default` type classes which returns a default value for a given type 

```scala
trait Default[A] {
  def value: A
}
```

I have instances defined for basic types. I would like to derive a `Default` type class instance for my `Users`

## implicitly, macro time ?

Writing this explicitly would look something like this

```scala
class UsersDefault extends Users[Default] {
    override def login(
      username: Refined[String, Email],
      password: Refined[String, Password]
    ): Default[Option[ExchangeResult]] = implicitly
    override def register(
      user: User,
      password: Refined[String, Password]
    ): Default[Option[UserId]] = implicitly
  }
```

As you can see everything is `implicitly`. Could we use a scalamacro for that to generate such a class?

Ideally I would sub class this such that I can inherit and override certain methods. 

## lifting

Since we a `Default` type class instance for `Users` now I would like to lift the values inside the `Applicative`. This is a matter of writing a natural transformation of `Default ~> F` where `F[_] : Applicative`. This is easy, but how would that work with sub classing? e.g. pseudo code:

```scala
object Dummy {

   implicit def defaultToApplicative[F[_] : Applicative]: Default ~> F = ???


   // this class would extend the `Users` algebra and use the `defaultToApplicative` to find a instance of `Users[Default]` which can be turned in to `Users[F]` by applying the transformation
   @GenImpl(Users)
   class DummyUsers[F[_] : Applicative]
}
```

I would rather avoid using scalameta, as it breaks with scoverage

# Closing words

This a rough sketch and a thought experiment to solve the problem. There might be other solutions as well, happy to hear your thoughts!

**Comment by kailuowang** [comment]
Apologize in advance that I am replying from my phone. Thanks for this detailed explanations. I think it should be pretty easy to write a macro that generates an empty interpreter for an algebra for a `F[_] : EmptyK`, EmptyK is a lawless class defined in Alleycats. Similarly, we can add a OneK there to better fit your test semantics, and write a macro that generates interpreters for that.
I agree we don't want to add more stuff that depends on Scalameta. The migration to Scala macro is on the agenda but we still don't know when that's going to happen.

**Comment by joroKr21** [comment]
As far as I understood the main use case is for testing. Wouldn't then be enough to just implement all methods with `???` - it's easy to create such a value, but the difficult part is actually creating a new class that can be extended.

**Comment by Fristi** [comment]
Yes I did that :-) 

However due several refactorings I don't have a need for this anymore, closing this for now
