### ISSUE TITLE
Can't derive builder-style methods

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats-tagless#36]
```scala
trait Example[F[_]] {
  def unit: F[Unit]
  def withFoo(foo: String): Example[F]
}

object Example {
  import cats.tagless._
  implicit val exampleFunctorK: FunctorK[Example] = Derive.functorK[Example]
}
```

Gives
```
Error:scalac: overriding method withFoo in trait Example of type (foo: String)mypkg.pkg.Example[G];
 method withFoo has incompatible type
```

There's a trivial manual implementation here:
```scala
implicit val exampleFunctorK: FunctorK[Example] = new FunctorK[Example] {
  def mapK[F[_], G[_]](af: Example[F])(fk: F ~> G): Example[G] =
    new Example[G] {
      def unit: G[Unit] = fk(af.unit)
      def withFoo(foo: String): Example[G] =
        exampleFunctorK.mapK(af.withFoo(foo))(fk)
    }
  }
}
```

**Comment by joroKr21** [comment]
Maybe not quite a duplicate but in the same vein as #10

**Comment by joroKr21** [comment]
Hmm note that the "trivial manual implementation" would always overflow the stack.
This would only make sense if we return something other than `Example[F]`.

**Comment by Daenyth** [comment]
> always overflow the stack.

I'm not seeing how - can you point it out? I use something pretty close to this

**Comment by joroKr21** [comment]
Hmm I just tried it out and indeed it doesn't overflow the stack.
It looked to me from the definition that `exampleFunctorK.mapK(example)(fk).withFoo("foo")` would keep calling `mapK` forever but that's not the case.
