### ISSUE TITLE
Release for 2.13.0-RC1

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-tagless#39]
2.13 is weeks away, we should try to get cats-tagless to build with it already :)

**Comment by joroKr21** [comment]
I guess we would have to wait for catalyst. Is there something else? :thinking:

**Comment by kubukoz** [comment]
AFAICS catalysts might not be blocked anymore, btw: https://github.com/typelevel/catalysts/issues/27

**Comment by kailuowang** [comment]
Cats-tagless should probably follow cats and cats-effect and remove dep on catalyst. I will look into this

**Comment by kailuowang** [comment]
0.6 released
