### ISSUE TITLE
Invalid link in docs for `InvariantK`

### ISSUE THREAD

**Issue by vasiliybondarenko** [typelevel/cats-tagless#420]
I spotted invalid link https://typelevel.org/cats-tagless/typeclasses.md#invariantK in [docs](https://typelevel.org/cats-tagless/)

**Comment by joroKr21** [comment]
Oh good catch 👍

**Comment by vasiliybondarenko** [comment]
Seems like there are other invalid links in this page, like this https://typelevel.org/cats-tagless/typeclasses.md#semigroupalK

**Comment by joroKr21** [comment]
Hmm where do you find those links in the page exactly? I'm struggling a bit to find them.

**Comment by vasiliybondarenko** [comment]
<img width="1061" alt="Screenshot 2023-04-11 at 16 41 14" src="https://user-images.githubusercontent.com/3534883/231181903-fc1d2ed4-d126-456e-bf4e-bc23c31862ba.png">
<img width="1099" alt="Screenshot 2023-04-11 at 16 40 40" src="https://user-images.githubusercontent.com/3534883/231181912-6ba4bba9-cfca-46cb-b749-47ee64ab6ebb.png">

**Comment by joroKr21** [comment]
Wow that totally doesn't look like a link at all 🙈

**Comment by joroKr21** [comment]
Well the obvious issue is that the link points to`.md` files but on the website of course we have `.html` files.
That is easily fixed but I don't think I ever published the microsite. @kailuowang do you remember how to do that?

**Comment by joroKr21** [comment]
Ah I think I just need to push to the `gh-pages` branch
