### ISSUE TITLE
Profunctor/Bifunctor derivation

### ISSUE THREAD

**Issue by joroKr21** [typelevel/cats-tagless#48]
Adding an `@autoProfunctor` annotation would require reworking `AlgDefn` a bit to handle a list of type parameters instead of only one.

**Comment by LukaJCB** [comment]
We could probably derive bifunctor in a similar way :)

**Comment by marcin-rzeznicki** [comment]
Good idea! I can try to add that some time next week, now that I have quite recent understanding of the code base

**Comment by joroKr21** [comment]
> We could probably derive bifunctor in a similar way :)

Indeed. Bifunctors are really popular these days :smile: 

@marcin-rzeznicki I have an old branch that adds `Derive.profunctor`, but not the annotation.
I will add some tests and make a PR soon.

**Comment by milessabin** [comment]
> We could probably derive bifunctor in a similar way :)

For reference: https://github.com/dotty-staging/dotty/blob/4e434e0f7a6b0f62dc39db19c3b65139723d7548/tests/typeclass-derivation/typeclass-derivation-4-split/TypeClasses_3.scala#L136-L181.

**Comment by marcin-rzeznicki** [comment]
Thanks @milessabin . Also thanks for the PR @joroKr21

**Comment by marcin-rzeznicki** [comment]
BTW we could change the tile and mention `Bifunctor` /

**Comment by marcin-rzeznicki** [comment]
Sorry for the long delay. I was attending a Haskell conference for about a week plus had things to do in my work :smile:  I'm on it now - will PR soon.

**Comment by marcin-rzeznicki** [comment]
I think we can close this. Thanks @kailuowang @joroKr21

**Comment by joroKr21** [comment]
Resolved in #57, thanks @marcin-rzeznicki!
