### ISSUE TITLE
autoInvariantK fails when function takes lambda

### ISSUE THREAD

**Issue by Katrix** [typelevel/cats-tagless#52]
`@autoInvariantK` fails on this code

```scala
@autoInvariantK
trait InvariantFail[F[_]] {

  def function(f: String => F[Boolean]): F[Boolean]
}
```

Error
```
[error] object creation impossible, since method function in trait InvariantFail of type (f: String => G[Boolean])G[Boolean] is not defined
[error] method function overrides nothing.
[error] Note: the super classes of <$anon: ore.auth.InvariantFail[G]> contain the following, non final members named function:
[error] def function(f: String => G[Boolean]): G[Boolean]
[error] object creation impossible, since method function in trait InvariantFail of type (f: String => G[Boolean])G[Boolean] is not defined
[error] method function overrides nothing.
[error] Note: the super classes of <$anon: ore.auth.InvariantFail[G]> contain the following, non final members named function:
[error] def function(f: String => G[Boolean]): G[Boolean]
[error] four errors found
```

**Comment by joroKr21** [comment]
Yes, there is no support yet for algebras where the type parameter `F[_]` is nested in a compound type. See #10. I think it will be possible to implement, given that we have an instance of `InvariantK[λ[f[_] => String => f[Boolean]]]` (which can be defined). That's one of the next things on my list to try, but I'm not there yet. Ofc anyone is free to beat me to it :smile: 

There is also a lot to be improved on the error reporting, which is currently non existent. The macros are optimistic and they just rely on scalac to catch whatever wouldn't work. Ideally they should detect at least the most common errors and issue semantically meaningful messages.

We should also add a cheat sheet or a table to the documentation that summarizes the constraints for deriving each typeclass.

**Comment by joroKr21** [comment]
The error on the #56 branch is:
```scala
[error] could not find implicit value of type cats.tagless.InvariantK[[F[_]]String => F[Boolean]]
[error]   @autoInvariantK
[error]    ^
```
And once we define this instance in scope it works:
```scala
implicit def functorKforFunction[A, B]: FunctorK[λ[F[_] => A => F[B]]] =
    new FunctorK[λ[F[_] => A => F[B]]] {
      def mapK[F[_], G[_]](af: A => F[B])(fk: F ~> G) = a => fk(af(a))
    }
```

:tada:
