### ISSUE TITLE
Decide what to do about fullyRefined instances

### ISSUE THREAD

**Issue by joroKr21** [typelevel/cats-tagless#59]
Currently only `autoFunctorK` and `autoInvariantK` define fully refined instances in a special `fullyRefined` object inside the companion object of algebras.

We have at least three options:

1. Generate only fully refined instances:
    - :+1: No awkward imports, everything is in the companion object.
    - :-1: It's not clear if that would work in all cases (needs investigation).

2. Add a `fullyRefined` flag to macro annotations:
    - :+1: Easy to opt-in / opt-out for users.
    - :+1: Easy to distinguish which annotations support fully refined instances.
    - :-1: More complexity on both implementation and usage sides.

3. Automatically decide whether to generate fully refined instances based on the presence of type members:
    - :+1: Less overhead for algebras without type members.
    - :+1: Fully automatic, no need for special flags.
    - :-1: No way to opt-out for users.
    - :-1: Removing all type members later might cause imports to stop compiling.

**Comment by kailuowang** [comment]
I am on my phone, but IIRC fully refined instance is not usable when an instance for the existential type (i.e. not fully refined) is expected, because FunctorK is not covariant on the Alg type. 
I think I would vote for option 2, because to me this advanced feature justify some manual control by users.

**Comment by marcin-rzeznicki** [comment]
I agree with @kailuowang :+1:

**Comment by joroKr21** [comment]
> I am on my phone, but IIRC fully refined instance is not usable when an instance for the existential type (i.e. not fully refined) is expected, because FunctorK is not covariant on the Alg type.

In that case we could put the fully refined instances directly in the companion object, regardless of whether or not we use a feature flag.

**Comment by joroKr21** [comment]
At this point `fullyRefined` is legacy that is relevant for Scala 2 only. It will remain as it is for backwards compatibility but there is no point to expand it as it's not possible on Scala 3.
