### ISSUE TITLE
Migrate to mdoc

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats-tagless#62]

**Comment by joroKr21** [comment]
What's the advantage over `sbt-microsite`?

**Comment by LukaJCB** [comment]
`sbt-microsites` supports both tut and mdoc nowadays :) 
https://47deg.github.io/sbt-microsites/docs/settings.html

**Comment by kailuowang** [comment]
I would wait on it supports 2.13
https://github.com/scalameta/mdoc/issues/156

It's actually blocking sbt-microsite from supporting 2.13 at the moment.

**Comment by kailuowang** [comment]
BTW, by tracking that mdoc issue, I noticed that mdoc has more dependencies than `tut` and some of them depends on `Cats`, not necessarily a deal breaker for cats-tagless though.

**Comment by olafurpg** [comment]
FWIW, mdoc itself doesn't depend on cats but we have dependencies in our test suite that depend on cats.

**Comment by olafurpg** [comment]
mdoc v1.3.2 is out now with 2.13 support

**Comment by joroKr21** [comment]
@larsrh what does "lsug" mean?

**Comment by joroKr21** [comment]
Does anyone know how to republish the site?

**Comment by kailuowang** [comment]
> Does anyone know how to republish the site?

If you have dependencies installed locally (namely ruby and jekyll) you can just run sbt publishMicrosite
More information on sbt-microsite website.

**Comment by joroKr21** [comment]
I was too quick to be happy - needed some fixes in #191
The problem was that importing `autoDerive._` from different algebras in the same scope cause a name clash.

**Comment by joroKr21** [comment]
Looks nice: https://typelevel.org/cats-tagless/ 🥳

**Comment by larsrh** [comment]
> @larsrh what does "lsug" mean?

I prepared this as a ticket to work on at https://www.lsug.co.uk/meetups/2021-01-30

**Comment by larsrh** [comment]
Ah, and I just saw that there was already a PR for it, so this wouldn't have been a good pick anyway.
