### ISSUE TITLE
Example of build.sbt for 2.12/2.13 cross compile?

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats-tagless#63]
The readme mentions to only use the compiler plugin on 2.12 - how should build.sbt be set up for a project that's cross-building 2.13 and 2.13?

**Comment by kailuowang** [comment]
You can find examples in many OSS projects , e.g. cats. A PR to the readme would be great!

**Comment by Daenyth** [comment]
Note to self for later: https://github.com/typelevel/cats/blob/master/build.sbt#L90
