### ISSUE TITLE
Semiauto Derivation

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/cats-tagless#8]
It would be very nice to use this with a semiauto encoding in the companion objects. I know circe and shapeless does something like this for Encoder/Decoder/Generic and I'm unsure if it  could be leveraged with the existing macro definitions to create something like the below encoding

```scala
implicit val functorKAlg = deriveFunctorK[MyAlgebra]
```

**Comment by kailuowang** [comment]
Would you mind giving a use case? Currently it's not really a derivation, it's just automatically generated code per algebra trait.

**Comment by ChristopherDavenport** [comment]
Totally, what I mean is that I would like the auto generated code to be explicitly reference-able and rather than operating with macro magic around the initial trait declaration do that at a location of my choice. (Although personally I would always put this in the companion object.)

Many of my algebras I would look like the following 

```scala
trait DoSomethingAlgebra[F[_]]
   def doSomething: F[Int]
}
object DoSomethingAlgebra {
   def impl[F[_]: Applicative] = new DoSomethingAlgebra[F[_]]{
      def doSomething : F[Int] = Applicative[F].pure(1)
   }
   // What I would like for easily being able to reference and explicitly say
   // what is happening in my application code. Now the macro is expanding to
   // an explicitly stated type in an explicitly stated location. The macro 
   // magic is in the generated code. Derive May be the wrong word, but 
   // the intent of semiauto generation is hopefully clearer.
   implicit val functorKDoSomething : FunctorK[DoSomethingAlgebra] =
     deriveFunctorK[DoSomethingAlgebra]
   implicit val semigroupalKDoSomething : SemigroupalK[DoSomethingAlgebra] = 
     deriveSemigroupalK[DoSomethingAlgebra]
}
```

**Comment by kailuowang** [comment]
It makes sense. I am not a huge fan of macro annotation myself. I guess that's possible to make a `deriveFunctorK` macro, although I don't know that much of macro to have a say.

**Comment by Odomontois** [comment]
Sounds like it needs macro rewrite to reflection-based version, since scalameta def-macro probably wasn't merged by @xeno-by

**Comment by joroKr21** [comment]
This could be part of a migration path towards a `scala.reflect` based solution as I proposed in #6

**Comment by fommil** [comment]
@ChristopherDavenport What you want is basically what `@deriving` already does (see https://github.com/scalaz/scalaz-deriving) ... it just needs to have a blackbox macro to point at for these specialist typeclasses. It might need a little tweak to support the Kind, but that should be easy enough.

Read in particular the sentence beginning "You can provide your own project-specific wirings "
