### ISSUE TITLE
Provide instances for cats core types

### ISSUE THREAD

**Issue by Odomontois** [typelevel/cats-tagless#9]
e.g. 
`FunctorK` for `EitherT`, `StateT`, `WriterT`,`Kleisli`
`InvariantK` for `Functor`, `Apply`, `FlatMap`, etc...
I wonder if they are welcomed in the companion or separate module?

**Comment by LukaJCB** [comment]
I think they're welcome here, even though they're not really a part of the `tagless` part of this library. WDYT @kailuowang? :)

**Comment by kailuowang** [comment]
We had numerous attempts of adding a `FunctorK` like type class and instances for those data types before. One of them is https://github.com/typelevel/cats/pull/1815

Since all these data types already have a unified `mapK` (see https://github.com/typelevel/cats/pull/2000
), there wasn't much use cases for adding such a type class. Do you see any use case for them in the context of final tagless?

**Comment by Odomontois** [comment]
Sometimes I'm using definitions like
```scala
trait SomeService[F[_]]{
  def actionA(...): EitherT[F, ErrorA, ResultA]
  def actionB(...): EitherT[F, ErrorB, ResultB]
}
```
`EitherT`  comparing to simple `F[Either[Error, Result]]`  has nice distinction for the following implicit analysis, so along with #10 it could provide great help with keep such definitions along with `@autoFunctorK`

I'm aware that Either is definitely tagged, and there could be some alternatives like
* make those def even more tagless like 
   ```scala
   def actionA[A: ErrorA](...): F[A]
   def actionB[B: ErrorB](...): F[B]
  ```
* split definitions to different services so I can define
  ``` trait SomeServiceA[F[_]]{
     def action(...): F[ResultA]
  ```
  ```
    def someServiceAImpl[F[_]: Raise[?[_], ErrorA : ...]: F[SomeServiceA[F]]
  ```

Both these approached along with direct support of `EitherT` are considerable, I'm just trying to find most elegant and natural solution for the problem

**Comment by joroKr21** [comment]
That would work nicely together with #10
